import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";

/**
 * Global setup for integration tests, now that the app runs on Postgres.
 *
 * Strategy: rather than touch any real database, we carve out a throwaway
 * Postgres *schema* (namespace) inside whatever server TEST_DATABASE_URL (or
 * DATABASE_URL) points at, push the Prisma schema into it, and drop it on
 * teardown. Each run gets a unique schema name, so parallel/overlapping runs
 * never collide and nothing leaks into `public`.
 *
 * If no Postgres URL is configured, the suite is skipped gracefully — see the
 * `INTEGRATION_DB_READY` flag, which the test files gate on with skipIf().
 * That keeps `npm run test:integration` green on a dev box with no database
 * instead of erroring out with a connection refused.
 *
 * Vitest runs this once in the main process before workers fork; the env vars
 * we set here are inherited by those forked workers (pool: "forks").
 */
export default async function setup() {
  const base = process.env.TEST_DATABASE_URL || process.env.DATABASE_URL || "";

  // Only Postgres is supported now. No URL, or a non-Postgres one (e.g. the
  // legacy SQLite `file:` fallback), means "skip integration tests".
  if (!/^postgres(ql)?:\/\//i.test(base)) {
    process.env.INTEGRATION_DB_READY = "0";
    console.warn(
      "[integration] no Postgres TEST_DATABASE_URL/DATABASE_URL set — skipping integration suite.\n" +
        "             set e.g. TEST_DATABASE_URL=postgresql://user:pass@host:5432/dbname to run it.",
    );
    return async () => {};
  }

  // Unique, valid SQL identifier for this run's schema.
  const schema = `test_${randomBytes(6).toString("hex")}`;

  const url = new URL(base);
  url.searchParams.set("schema", schema);
  const dbUrl = url.toString();
  process.env.DATABASE_URL = dbUrl;
  process.env.INTEGRATION_DB_READY = "1";

  // Push the schema into the fresh namespace. `prisma db push` creates the
  // schema if it doesn't exist. --skip-generate: the client is already
  // generated by the regular install.
  execSync(`npx prisma db push --skip-generate --accept-data-loss --schema=./prisma/schema.prisma`, {
    env: { ...process.env, DATABASE_URL: dbUrl },
    stdio: "pipe",
  });

  return async () => {
    // Drop the throwaway schema and everything in it. Imported lazily so the
    // skip path above never spins up a Prisma client.
    const { PrismaClient } = await import("@prisma/client");
    const client = new PrismaClient({ datasources: { db: { url: dbUrl } } });
    try {
      await client.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
    } finally {
      await client.$disconnect();
    }
  };
}
