import { execSync } from "node:child_process";
import { mkdtempSync, rmSync, existsSync } from "node:fs";
import path from "node:path";
import os from "node:os";

/**
 * Global setup: spin up a temporary SQLite DB per integration run and push
 * the Prisma schema to it. Sets DATABASE_URL before any test file imports
 * the Prisma client.
 *
 * Vitest calls setup() once before all tests; the returned function is
 * teardown.
 */
export default async function setup() {
  const dir = mkdtempSync(path.join(os.tmpdir(), "homelab-integration-"));
  const dbPath = path.join(dir, "test.db");
  const url = `file:${dbPath}`;
  process.env.DATABASE_URL = url;

  // Push the schema. --skip-generate because the client is already
  // generated by the regular install; we just want the SQLite file populated.
  execSync(`npx prisma db push --skip-generate --accept-data-loss --schema=./prisma/schema.prisma`, {
    env: { ...process.env, DATABASE_URL: url },
    stdio: "pipe",
  });

  return async () => {
    if (existsSync(dir)) rmSync(dir, { recursive: true, force: true });
  };
}
